name = "google-chat-proxy"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "f4fb1f9993ac7a8d90e0cc74835eca76"

[vars]
FIREBASE_PROJECT_ID = "cb-hr-4b503"
ALLOWED_HQ_IDS = "hq-cloud"
ALLOWED_ORIGINS = "http://localhost:5178,http://localhost,https://cb-hr-4b503.firebaseapp.com,https://cb-hr-4b503.web.app"
